
package vistas;

import java.awt.Dimension;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH); // para que inicie con la pantalla completa
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        VentanaPrincipal = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        subMenuSalir = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuGenerarVenta = new javax.swing.JMenuItem();
        menuCliente = new javax.swing.JMenu();
        menuClientes = new javax.swing.JMenuItem();
        menuProducto = new javax.swing.JMenuItem();
        menuVendedor = new javax.swing.JMenuItem();
        menuGenerarReporte = new javax.swing.JMenu();
        menuGenerarReportes = new javax.swing.JMenuItem();
        menuReporteVentas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout VentanaPrincipalLayout = new javax.swing.GroupLayout(VentanaPrincipal);
        VentanaPrincipal.setLayout(VentanaPrincipalLayout);
        VentanaPrincipalLayout.setHorizontalGroup(
            VentanaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 507, Short.MAX_VALUE)
        );
        VentanaPrincipalLayout.setVerticalGroup(
            VentanaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 298, Short.MAX_VALUE)
        );

        subMenuSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/home.png"))); // NOI18N
        subMenuSalir.setText("Menú");
        subMenuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuSalirActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Ayuda");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        subMenuSalir.add(jMenuItem1);

        jMenuItem2.setText("Salir");
        subMenuSalir.add(jMenuItem2);

        jMenuBar1.add(subMenuSalir);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/logoventas.png"))); // NOI18N
        jMenu2.setText("Ventas");

        menuGenerarVenta.setText("Generar Venta");
        menuGenerarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGenerarVentaActionPerformed(evt);
            }
        });
        jMenu2.add(menuGenerarVenta);

        jMenuBar1.add(jMenu2);

        menuCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/logomanten.png"))); // NOI18N
        menuCliente.setText("Mantenimiento");

        menuClientes.setText("Cliente");
        menuClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuClientesActionPerformed(evt);
            }
        });
        menuCliente.add(menuClientes);

        menuProducto.setText("Producto");
        menuProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProductoActionPerformed(evt);
            }
        });
        menuCliente.add(menuProducto);

        menuVendedor.setText("Vendedor");
        menuVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuVendedorActionPerformed(evt);
            }
        });
        menuCliente.add(menuVendedor);

        jMenuBar1.add(menuCliente);

        menuGenerarReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/reportes.png"))); // NOI18N
        menuGenerarReporte.setText("Reportes");

        menuGenerarReportes.setText("Reporte General");
        menuGenerarReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGenerarReportesActionPerformed(evt);
            }
        });
        menuGenerarReporte.add(menuGenerarReportes);

        menuReporteVentas.setText("Reporte de Ventas");
        menuReporteVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuReporteVentasActionPerformed(evt);
            }
        });
        menuGenerarReporte.add(menuReporteVentas);

        jMenuBar1.add(menuGenerarReporte);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(VentanaPrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(VentanaPrincipal)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void subMenuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuSalirActionPerformed
        /**
         * salir del sistema
         */
        System.exit(0);
    }//GEN-LAST:event_subMenuSalirActionPerformed

    private void menuGenerarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGenerarVentaActionPerformed
        // instanciar formlario de ventas
        VentasForm vf = new VentasForm();
        //VentanaPrincipal.add(vf);
        //vf.setVisible(true);
        CentrarVentana(vf);
        
    }//GEN-LAST:event_menuGenerarVentaActionPerformed

    private void menuClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuClientesActionPerformed
        ClienteForm cf = new ClienteForm();
        CentrarVentana(cf);
    }//GEN-LAST:event_menuClientesActionPerformed

    private void menuProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProductoActionPerformed
        ProductosForm pf = new ProductosForm();
        CentrarVentana(pf);
    }//GEN-LAST:event_menuProductoActionPerformed

    private void menuVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuVendedorActionPerformed
        VendedorForm vnf = new VendedorForm();
        CentrarVentana(vnf);
    }//GEN-LAST:event_menuVendedorActionPerformed

    private void menuGenerarReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGenerarReportesActionPerformed
        // abrir la tbla de reporte generañ
        ReporteForm reporte = new ReporteForm();
        abrirReportes(reporte);
    }//GEN-LAST:event_menuGenerarReportesActionPerformed

    private void menuReporteVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuReporteVentasActionPerformed
        // abrir la tabla de reporte detallado
        ReporteVentasForm repventas = new ReporteVentasForm();
        abrirReportes(repventas);
    }//GEN-LAST:event_menuReporteVentasActionPerformed

    void CentrarVentana(JInternalFrame frame)
    {
        /**
         * función para centrar las ventanas de formuarios
         */
        VentanaPrincipal.add(frame); //agregar el formulario enviado por parametro a la ventana principal
        Dimension dimension = VentanaPrincipal.getSize();
        Dimension Dframe = frame.getSize();
        frame.setLocation((dimension.width - Dframe.height)/2, ((dimension.height - Dframe.width)/2)+10);
        frame.show();
    }
    
    void abrirReportes(JInternalFrame frame)
    {
        VentanaPrincipal.add(frame);
        frame.setLocation(200, 100);
        frame.show();
    }
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane VentanaPrincipal;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenu menuCliente;
    private javax.swing.JMenuItem menuClientes;
    private javax.swing.JMenu menuGenerarReporte;
    private javax.swing.JMenuItem menuGenerarReportes;
    private javax.swing.JMenuItem menuGenerarVenta;
    private javax.swing.JMenuItem menuProducto;
    private javax.swing.JMenuItem menuReporteVentas;
    private javax.swing.JMenuItem menuVendedor;
    private javax.swing.JMenu subMenuSalir;
    // End of variables declaration//GEN-END:variables
}
